name: 'Commit Message Check'
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, edited, reopened, synchronize ]
  push:
    branches:
      - "^(?!develop|main).+"

jobs:
  validate-commit-message:
    name: Commit Message Validation
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Prefix
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(Merge|^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(.+)?:).+'
          error: 'Your first line has to contain a commit type like stated in feat:, docs:, etc..'
          excludeDescription: true
          excludeTitle: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
